AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "examples/**/*"
    - "tmp/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 60

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 30

Style/Documentation:
  Enabled: false
