# frozen_string_literal: true

source "https://rubygems.org"

# Use the local checkout of the gem (keeps the gem itself lightweight)
gem "powo_ruby", path: "../.."

gem "puma"
gem "rackup"
gem "sinatra"

